name: update

on:
  schedule:
    - cron: "0 10 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
      - name: Run
        id: run
        continue-on-error: true
        shell: bash -x {0}
        run: |
          cd JmaCodeDictionary/JmaCodeDictionaryGenerator
          dotnet run -c Release
          if [ $? -eq 1 ]; then
            git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
            git config --global user.email "ingen188@gmail.com"
            git config --global user.name "ingen084"
            git add ../../csv ../../.cache
            git commit -m "Update `date '+%Y.%m.%d'`"
            git push
            gh release `date '+%Y.%m.%d'`
          fi
